### ISSUE TITLE
Tas

### ISSUE THREAD

**Issue by bhopone** [shavitush/Oryx-AC#12]
When playing on TAS mode (btimer's tas) you cannot strafe because oryx is blocking it (  [ORYX] Cheat: +klook usage | Level: HIGH-NOKICK )
How can I disable this?

**Comment by shavitush** [comment]
I can't support bTimes for this exact reason :/ - it being paid software doesn't make it any better. I'll try to contact blacky and see if he can hook me up with the .inc files so that I can support it.

**Comment by shavitush** [comment]
Quick update: talked to blacky. I'll be adding bTimes support soon and have everything in a single package rather than a per-timer definition setup.

**Comment by shavitush** [comment]
@bhopone can you try the v1.3 build and see if it fixes the issue? https://github.com/shavitush/Oryx-AC/pull/13

[oryx_1.3.zip](https://github.com/shavitush/Oryx-AC/files/1936749/oryx_1.3.zip)

**Comment by bhopone** [comment]
Okay tas is working now thanks! Only problem i have is that bad players will get flagged by ac but good players/cheaters will not get flagged (for example it doesn't flag pake)

**Comment by cytrus224** [comment]
Disable oryx sanity @bhopone , it has one broken detection.
