### ISSUE TITLE
Bash-checking logic allows users to gerrymander their stats.

### ISSUE THREAD

**Issue by Nolan-O** [shavitush/Oryx-AC#8]
I handled this as a frame-count cooldown in the `OnGameFrame()` callback so that users couldn't group their stats into multiples of of the strafe history threshold. If they know exactly which strafes will be sampled in each analysis, they can squeeze out notably better stats than if they didn't.

For example, a scenario in which a single outlier strafe offset can be created to prevent a detection does not reliably work _unless_ the user knows when their analysis takes place.

**Comment by shavitush** [comment]
Ah, I see now. Thanks for reaching out to me!
